spring:
  application:
    name: backend-api
  profiles:
    active: dev,local
  # 通用默认配置
  jpa:
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always # 始终尝试初始化，具体脚本由 profile 决定是否覆盖

server:
  port: 8090

app:
  material-price-fetch:
    enabled: true
    cron: "0 10 2 * * *"
    zone: "Asia/Shanghai"
